### PR TITLE
mkcode.go: add IN/OUT/OPT... information of parameters as comment to func

### PR DESCRIPTION
**Pull request by oec**
Hi,

I adapted mkcode.go to use the Direction-information that was already extracted (_In_, _Out_, _InOpt_, etc.) and put it as comments before a func-declaration.  That way, a call to 'go doc ..." reveals that information about the positional parameters, f.e.:

     % go doc oec/go-ntdll.NtQueryDirectoryObject
     package ntdll // import "github.com/oec/go-ntdll"
     
     func NtQueryDirectoryObject(DirectoryHandle Handle,
             Buffer *byte,
             Length uint32,
             ReturnSingleEntry bool,
             RestartScan bool,
             Context *uint32,
             ReturnLength *uint32) NtStatus
         OUT-parameter: Buffer, ReturnLength. INOUT-parameter: Context.
        *OPT-parameter: Buffer, ReturnLength.

The positional parameters are also printed with newlines to increase readability.

In addition, a special case in atom.go (which contains a positional parameter whose name is followed by the string 'OPTIONAL') is handled properly.

Cheers,
Özgür

### CODE REVIEW

**Comment by rasa** [comment]
I haven't tested this, but it looks great. You might consider removing your previous PR from 0b0e7dc.

**Comment by oec** [comment]
I wasn't sure if @hillu would accept both CRs, so I wait for his decision/comments. The patches are orthogonal so far and can be applied individually or both at the same time.

**Comment by oec** [comment]
I wasn't sure if @hillu would accept both CRs, so I wait for his decision/comments. The patches are orthogonal so far and can be applied individually or both at the same time. Github shows the accumulative changes to my base line instead of hillu's but that can be adjusted at merge time.

**Comment by oec** [comment]
Oh, I just noticed that the OPTIONAL string in atom.go was probably an error.  It seems like a leftover from the function signature ntinternals.net that wasn't transformed into a _In_opt_.  I'll close this pull request and will open another one with the original issue fixed.

**Pull request closed without merging**
