### PR TITLE
Add io and rtl files, support BOOLEAN retvals, more

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Comment by rasa** [comment]
OK, I fixed the .gitignore issues. Thanks for considering this PR.

**Comment by hillu** [comment]
Regarding io and rtl: I had bunch of file- and process/section-related functions still lying around. I suppose I'll commit those first and merge what's still missing later.

**Comment by rasa** [comment]
That's fine. Thanks for working on that.

**Comment by hillu** [comment]
I believe I have everything sorted out.

**Pull request closed without merging**
